#
# This pipeline needs the following tasks from Tekton Catalog
#   - git-clone
#   - flake8
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline

spec:
  workspaces:
    - name: pipeline-workspace

  params:
    - name: repo-url
    - name: branch
      default: main
    - name: build-image

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      runAfter:
        - init
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: lint
      runAfter:
        - clone
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - --count
            - --max-complexity=10
            - --max-line-length=127
            - --statistics

    - name: tests
      runAfter:
        - clone
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"

    - name: build
      runAfter:
        - tests
        - lint
      taskRef:
        name: buildah
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: "$(params.build-image)"

    - name: deploy
      runAfter:
        - build
      taskRef:
        name: openshift-client
        kind: ClusterTask
      workspaces:
        - name: manifest-dir
          workspace: pipeline-workspace
      params:
        - name: SCRIPT
          value: |
            echo "Updating manifest..."
            sed -i "s|IMAGE_NAME_HERE|$(params.build-image)|g" deploy/deployment.yaml
            cat deploy/deployment.yaml
            echo "Deploying to OpenShift..."
            oc apply -f deploy/
            oc get pods -l app=accounts